session_name: terraform-edu
windows:
- focus: 'true'
  layout: 8b1d,238x58,0,0{119x58,0,0[119x42,0,0,1,119x15,0,43,2],118x58,120,0[118x42,120,0,3,118x15,120,43,4]}
  options: {}
  start_directory: ~/repos/terraform-edu/
  panes:
  - focus: 'true'
    shell_command:
    - vim
  - shell_command:
    - cd stage/services/web/
    - clear
  - shell_command:
    - cd ../terraform-module-edu/
    - clear
    - vim
  - shell_command:
    - cd ../terraform-module-edu
    - clear
  window_name: terraform
- window_name: mockapp
  layout: 2f8b,238x58,0,0{119x58,0,0,5,118x58,120,0[118x42,120,0,6,118x15,120,43,7]}
  start_directory: ~/repos/terraform-mockapp-edu/
  options: {}
  panes:
  - focus: 'true'
    shell_command:
    - vim
  - shell_command:
    - clear
  - shell_command:
    - clear
