session_name: terraform-edu
windows:
- window_name: terraform
  focus: 'true'
  layout: 8b1d,238x58,0,0{119x58,0,0[119x42,0,0,1,119x15,0,43,2],118x58,120,0[118x42,120,0,3,118x15,120,43,4]}
  options: {}
  start_directory: ~/repos/terraform-edu/
  panes:
  - focus: 'true'
    shell_command:
    - vim
  - shell_command:
    - cd dev/
    - clear
  - shell_command:
    - cd ../terraform-module-edu/
    - clear
    - vim
  - shell_command:
    - cd ../terraform-module-edu
    - clear
- window_name: services
  layout: 8b1d,238x58,0,0{119x58,0,0[119x42,0,0,1,119x15,0,43,2],118x58,120,0[118x42,120,0,3,118x15,120,43,4]}
  options: {}
  start_directory: ~/repos/
  panes:
  - focus: 'true'
    shell_command:
    - cd terraform-svc-web-edu/
    - vim main.go
  - shell_command:
    - cd terraform-svc-web-edu/
    - clear
  - shell_command:
    - cd terraform-svc-run-edu/
    - vim main.go
  - shell_command:
    - cd terraform-svc-run-edu/
    - clear

