session_name: terraform-edu
windows:
- focus: 'true'
  layout: 166e,318x79,0,0{159x79,0,0[159x48,0,0,0,159x30,0,49,2],158x79,160,0[158x65,160,0,1,158x13,160,66,3]}
  options: {}
  start_directory: ~/repos/terraform-edu/
  panes:
  - focus: 'true'
    shell_command:
    - vim
  - shell_command:
    - cd stage/services/frontend-app/
    - clear
  - shell_command:
    - cd ../terraform-module-edu/
    - clear
    - vim
  - shell_command:
    - cd ../terraform-module-edu
    - clear
  window_name: edu
