version: 2
jobs:
  test-services-web:
    docker:
      - image: hashicorp/terraform
    working_directory: ~/project/stage/services/web/
    steps:
      - checkout
      - run:
          name: Install modules and plugins
          command: terraform init -upgrade
      - run: 
          name: Run terraform plan
          command: terraform plan

  test-databases-mysql:
    docker:
      - image: hashicorp/terraform
    working_directory: ~/project/stage/databases/mysql/
    steps:
      - checkout
      - run:
          name: Install modules and plugins
          command: terraform init -upgrade
      - run: 
          name: Run terraform plan
          command: terraform plan

workflows:
  version: 2
  init-and-plan:
    jobs:
      - test-services-web:
          filters:
            branches:
              only: master
      - test-databases-mysql:
          filters:
            branches:
              only: master
