version: 2
jobs:
  test-dev:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: Install modules and plugins
          command: |
            terraform init -upgrade
          working_directory: ~/project/dev/
      - run: 
          name: Run terraform plan
          command: |
            terraform plan -out /tmp/dev.plan
          working_directory: ~/project/dev/
      - store_artifacts:
          path: /tmp/dev.plan

workflows:
  version: 2
  init-and-plan:
    jobs:
      - test-dev:
          filters:
            branches:
              only: master
