version: 2

jobs:
  build:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: Install Modules and Plugins
          command: terraform init -upgrade
          working_directory: ~/project/stage/services/frontend-app/
      - run: 
          name: Run Terraform Plan
          command: terraform plan
          working_directory: ~/project/stage/services/frontend-app/


