version: 2

jobs:
  validate_terraform:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: Validate Terraform Formatting
          command: "[ -z \"$(terraform fmt -write=false)\" ] || { terraform fmt -write=false -diff; exit 1; }"

  build:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: Install Modules and Plugins
          command: terraform init -upgrade
          working_directory: ~/project/stage/services/frontend-app/
      - run: 
          name: Run Terraform Plan
          command: terraform plan
          working_directory: ~/project/stage/services/frontend-app/


