version: 2
jobs:
  aws-dev:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: Install modules and plugins
          command: |
            terraform init -upgrade
          working_directory: ~/project/aws/
      - run:
          name: Run terraform validate
          command: |
            terraform validate
          working_directory: ~/project/aws/
      - run: 
          name: Run terraform plan
          command: |
            terraform plan -out /tmp/default.plan 
          working_directory: ~/project/aws/
      - store_artifacts:
          path: /tmp/default.plan

workflows:
  version: 2
  init-and-plan:
    jobs:
      - aws-dev:
          filters:
            branches:
              only: master
