version: 2
jobs:
  test-services-web:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: Install modules and plugins
          command: |
            terraform init -upgrade
          working_directory: ~/project/stage/services/web/
      - run: 
          name: Run terraform plan
          command: |
            terraform plan -out /tmp/services-web.plan
          working_directory: ~/project/stage/services/web/
      - store_artifacts:
          path: /tmp/services-web.plan

  test-databases-mysql:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: Install modules and plugins
          command: |
            terraform init -upgrade
          working_directory: ~/project/stage/databases/mysql/
      - run: 
          name: Run terraform plan
          command: |
            terraform plan -out /tmp/database-mysql.plan
          working_directory: ~/project/stage/databases/mysql/
      - store_artifacts:
          path: /tmp/database-mysql.plan

workflows:
  version: 2
  init-and-plan:
    jobs:
      - test-services-web:
          filters:
            branches:
              only: master
      - test-databases-mysql:
          filters:
            branches:
              only: master
